version: '3.9'

services:
    api:
      image: bohdanshlyah/flask-api:latest
      restart: always
      ports:
        - "5000:5000"
      env_file: .env
      environment:
        - DB_USERNAME=$DB_USERNAME
        - DB_PASSWORD=$DB_PASSWORD
        - DB_HOSTNAME=$DB_HOSTNAME
        - DB_NAME=$DB_NAME
      depends_on:
        - db
    
    db:
      image: mysql:8.0.29
      volumes:
        - db_data:/var/lib/mysql
      restart: always
      env_file: .env
      environment:
        MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
        MYSQL_DATABASE: $DB_NAME
        MYSQL_USER: $DB_USERNAME
        MYSQL_PASSWORD: $DB_PASSWORD
volumes:
  db_data: {}